### ISSUE TITLE
Exception when using gem with rails 2.3.14

### ISSUE THREAD

**Issue by MikeEmery** [johnnyhalife/waz-storage#16]
Ruby -v

```
ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [i686-darwin11.3.0], MBARI 0x6770, Ruby Enterprise Edition 2012.02
```

Gemfile:

```
gem 'waz-storage'
```

Stack Trace:

```
[ pid=94274 thr=2266460460 file=utils.rb:176 time=2012-04-04 16:36:06.777 ]: *** Exception NoMethodError in PhusionPassenger::ClassicRails::ApplicationSpawner (super: no superclass method `require' for main:Object) (process 94274, thread #<Thread:0x10e2ee258>):
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@mskynet/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@mskynet/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:547:in `new_constants_in'
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@mskynet/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@mskynet/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:180:in `to_proc'
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@mskynet/gems/waz-storage-1.1.1/lib/waz-storage.rb:1:in `each'
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@mskynet/gems/waz-storage-1.1.1/lib/waz-storage.rb:1
from /Users/mike/.rvm/gems/ree-1.8.7-2012.02@global/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in `require'
```

I've tried this with both PhusionPassenger, WebBrick, and Mongrel and the result was the same.

**Comment by MikeEmery** [comment]
I've created a pull request to fix this https://github.com/johnnyhalife/waz-storage/pull/17.
